name: Ironman 2017
favicon: null
layout_spectrum: 0.39383
typography_spectrum: 0.17837
title: Treeniä yhden pienen päätöksen perässä
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-32992476-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d8002a'
    - '#ff0000'
    - '#aa0000'
    - '#800000'
  brandStrength: 0.4375
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.75
purpose:
  - name: follow
    item: null
    url: null
