typography_spectrum: 0.5487758711894218
color:
  brandColors:
    - '#ffffff'
    - '#d8002a'
    - '#ff0000'
    - '#aa0000'
    - '#800000'
  brandStrength: 0.07945647838894315
  lightness: 0.35426535651613356
  saturation: 0.1682027442236938
  rhythmicContrast: 0.46164367722365823
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2907998585069349
analytics:
  google: UA-32992476-3
  facebook: null
  twitter: null
author:
  name: Ferrix Hovi
name: Ironman 2018
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Projekti
    id: 6c2d5e9e-563a-40da-8265-49e1a64c6332
    type: content
favicon: null
title: IM18
content: []
description: Treeniä yhden pienen päätöksen perässä
purpose: []
