name: Ironman 2017
favicon: null
layout_spectrum: 0.33243
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d8002a'
    - '#ff0000'
    - '#aa0000'
    - '#800000'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.75
purpose:
  - name: follow
    item: null
    url: null
