name: Ironman 2018
favicon: null
layout_spectrum: 0.39383
typography_spectrum: 0.30614
title: IM18
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-32992476-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d8002a'
    - '#ff0000'
    - '#aa0000'
    - '#800000'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
content: []
description: Treeniä yhden pienen päätöksen perässä
github: true
author:
  name: Ferrix Hovi
